version: "1.0"
released: "2019-01-01T00:00:00Z"
update: true
jwt:
  enable: true
  signkey: TestForFasthttpWithJWT
  expiredAt: 5
  loadAccount: true
  accountFile: ../../config/jwt_account.yml
channel:
  transferqueue: 100
  logqueue: 100
webserver:
  port: "8080"
  tls: false
  certificateFile: webCert.pem
  keyFile: webKey.key
  maxrpc: 10
  maxlistenrpc: 1
  routingMode: 1
  nonceMode: 1
keys:
  loadKey: true
  accountfile: ../../config/account.yml
  keystore: ../../keystore
  password: "123456"
networks:
- name: host1
  http: 127.0.0.1:8501
  websocket: 127.0.0.1:8541
  local: 127.0.0.1
- name: host2
  http: 127.0.0.1:8502
  websocket: 127.0.0.1:8542
  local: 127.0.0.1
redis:
  maxconn: 100
  host: localhost:6379
  password: ""
  db: 0
rabbitmq:
  host: localhost
  port: 5672
  user: vinsmart
  password: 123456
  numPub: 2
  numSub: 2
  queues:
    request: "request"
    task: "tasks"
    processing: "processing"
    error: "error"
    result: "result"
contract:
  gasprice: "1"
  gaslimitdefault: 900000
  gaslimit:
    create: 900000
    credit: 900000
    debit: 900000
    deploy: 1000000
    register: 900000
    state: 900000
    tranfer: 900000
  ethBudget: ffbcd481c1330e180879b4d2b9b50642eea43c02
  owner: ffbcd481c1330e180879b4d2b9b50642eea43c02
  address: 0x5329860483faef566Cae32971475038448017f88
