version: '2.1'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: SuperSecr3t
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  grafana:
     image: grafana/grafana:6.5.0
     ports:
       - 3000:3000
